### ISSUE TITLE
how to send interval command via json? (Gen2 shelly)

### ISSUE THREAD

**Issue by vampywiz17** [Legobas/mqtt-timer#3]
hello there,

I would like to make a ringing with my gen 2 shelly. here my conf:

```
    timers:
    - id: 001
      time: 16:15
      description: duda_teszt
      interval: 5 sec
      topic: duda_nagycsarnok/rpc
      message: ['{"id":1, "src": "horn", "method": "Switch.Set", "params":{"id":0,"on":true}}', '{"id":1, "src": "horn", "method": "Switch.Set", "params":{"id":0,"on":false}}']
```

It not work. What the correct syntax if i want to send a json command with "on" and after 5 sec a "off" (with json format)

**Comment by vampywiz17** [comment]
ahh sorry i read the doc. wrong :)

It is the config that need to me:

```
    timers:
    - id: 001
      time: 17:00:00
      description: duda_teszt_be
      topic: duda_nagycsarnok/rpc
      message: '{"id":1, "src": "horn", "method": "Switch.Set", "params":{"id":0,"on":true}}'

    - id: 002
      time: 17:00:05
      description: duda_teszt_ki
      topic: duda_nagycsarnok/rpc
      message: '{"id":1, "src": "horn", "method": "Switch.Set", "params":{"id":0,"on":false}}'
~

```
